# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up R ${{ matrix.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - name: Install library on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install pandoc

      - name: Install library on MacOS
        if: runner.os == 'macOS'
        run: |
          brew install pandoc

      - name: Install library on Windows
        if: runner.os == 'Windows'
        run: |
          choco install pandoc

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "note")
        shell: Rscript {0}
